### ISSUE TITLE
UndefVarError: AbstractModel not defined

### ISSUE THREAD

**Issue by zlqs1985** [sglyon/presentations#1]
Hi, Spencer, When I try to replicate your code mccall.jl in jupyter notebook, the first block of code 

```
using QuantEcon, QuantEcon.Models
immutable McCall <: AbstractModel
    w::AbstractVector         # vector of wages
    F::AbstractVector         # probability of each w
    β::Float64                # discount factor
    c::Float64                # reservation wage
    v_accept::AbstractVector  # value of accepting at each wage

    # Constructor to fill in v_accpet.
    function McCall(w::AbstractVector=linspace(0.1, 50.0, 5000), # evenly spaced
                    F::AbstractVector=fill(1/size(w,1), size(w,1)),  # uniform
                    β::Real=0.95,
                    c::Real=10.0)
        new(w, F, β, c, w./(1 - β))
    end
end
```

send me an error message

```
LoadError: UndefVarError: AbstractModel not defined
while loading In[1], in expression starting on line 3
```

So what's the source of the problem and how to fix it? My Julia version is 0.4.2 and QuantEcon package has been installed.

**Comment by sglyon** [comment]
Hi @zlqs1985 thanks for reporting.

The problem here is that we have changed QuantEcon.jl since I gave this talk.

Specifically, we used to include a number of example models in the library, but have since moved these models out of the package. They now live in the QuantEcon.applications repository. 

Another issue is that the tools I was relying on in this presentation have been removed. Specifically, the function `solve_vf` that could do value function iteration to compute a solution does not exist anywhere anymore.

Sorry for that.
